CREATE TABLE `denucieja`.`denuncia_arquivo` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `ID_ARQUIVO` INT NOT NULL,
  `ID_DENUNCIA` INT NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `FK_DENUNCIA_ARQUIVO_ID_ARQUIVO_idx` (`ID_ARQUIVO` ASC),
  INDEX `FK_DENUNCIA_ARQUIVO_ID_DENUNCIA_idx` (`ID_DENUNCIA` ASC),
  CONSTRAINT `FK_DENUNCIA_ARQUIVO_ID_ARQUIVO`
    FOREIGN KEY (`ID_ARQUIVO`)
    REFERENCES `denucieja`.`arquivo` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_DENUNCIA_ARQUIVO_ID_DENUNCIA`
    FOREIGN KEY (`ID_DENUNCIA`)
    REFERENCES `denucieja`.`denuncia` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);
